// <auto-generated />
namespace RentCar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addColToCar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addColToCar));
        
        string IMigrationMetadata.Id
        {
            get { return "201804252312282_addColToCar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
